mysql:
  image: mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    - MYSQL_USER=serge
    - MYSQL_PASSWORD=Sasha8169
    - MYSQL_DATABASE=testDb
    - MYSQL_ROOT_PASSWORD=Sasha8169
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"